### ISSUE TITLE
Please define the license

### ISSUE THREAD

**Issue by matthewyancer** [mattbatwings/BatPU#5]
Hello Matt,

Really enjoyed your video on this. What is the license for the BatPU instruction set and the code shared here on github?

Cheers,
Matthew Yancer

**Comment by mattbatwings** [comment]
Not sure what you mean, but I think the answer is none. You can do whatever you want with it. I just wouldn't recommend trying to program the ingame cpu because there's no documentation

**Comment by matthewyancer** [comment]
Thanks for the quick response.

My understanding is that part of GitHub user agreement is that code posted publicly be allowed to be viewed by others and forked by them into their own repositories, but that it doesn't grant permission for others to modify the code by default. The original author of the code still has "all rights reserved". GitHub has an option to publish a license on your repository and makes suggestions on what might be a good fit based on how you want others to use your code if you don't want to stick with the "all rights reserved".

I'm working on a bytecode virtual machine running inside C# .NET that runs assembly language programs (no Minecraft and no Python in the mix) and I liked how your sample assembly programs and your instruction set worked. I'm planning to release my code to my GitHub repository this month under an open source license (Apache 2.0 license). If there's any overlap on my work and your work, even if its minimal, I didn't want to be open sourcing with a permissive license something that I didn't have the right to just in case. I do plan to note that I took inspiration from your video and work in my release.

Let me know if any of this doesn't sit well with you. I appreciate your willingness to let me reference your materials.

Thanks!

**Comment by mattbatwings** [comment]
Right, okay. Thanks for explaining that. That's perfectly fine by me. 

Unfortunately I can't give you *complete* legal satisfaction as I probably won't be setting up a license anytime soon, but please feel free to use/reference any of my repositories at any time

**Comment by matthewyancer** [comment]
Sounds great, thanks again
